import { and, desc, eq, gte, ilike, inArray, isNull, or, sql } from "drizzle-orm";
import { NextResponse } from "next/server";
import { getDatabase } from "@/db/client";
import { channels, clanMembers, clanMessages, clans, directConversationMembers, directMessages, members, messages, spaces, users } from "@/db/schema";
import { getCurrentUser } from "@/lib/auth";
import { getChannelPermissions } from "@/lib/space-permissions";
import { Permission, hasPermission } from "@/lib/permissions";
import { decodeDirectMessage, DIRECT_MESSAGE_ENVELOPE_PREFIX } from "@/lib/direct-message";
export async function GET(request:Request){const user=await getCurrentUser();if(!user)return NextResponse.json({message:"Требуется вход."},{status:401});const url=new URL(request.url),q=(url.searchParams.get("q")??"").trim(),kind=url.searchParams.get("kind")??"all",author=url.searchParams.get("author")??"",channel=url.searchParams.get("channel")??"",file=url.searchParams.get("file")==="1",after=url.searchParams.get("after")??"";if(q.length<2||q.length>100||!['all','messages','people','spaces','clans','files'].includes(kind))return NextResponse.json({message:"Укажите запрос от 2 до 100 символов."},{status:400});const date=after?new Date(after):null;if(date&&Number.isNaN(date.valueOf()))return NextResponse.json({message:"Некорректная дата."},{status:400});const pattern=`%${q.replace(/[\\%_]/g,"\\$&")}%`,db=getDatabase(),messageKind=kind==='all'||kind==='messages'||kind==='files',filesOnly=file||kind==='files';const fileMatch=sql`jsonb_array_length(coalesce(${messages.attachments},'[]'::jsonb)) > 0`;const clanFileMatch=sql`jsonb_array_length(coalesce(${clanMessages.attachments},'[]'::jsonb)) > 0`;
 const [people,servers,clanRows,serverMessages,clanChat,directChat]=await Promise.all([
  ['all','people'].includes(kind)?db.select({id:users.id,label:users.displayName,sub:users.username}).from(users).where(or(ilike(users.displayName,pattern),ilike(users.username,pattern))).limit(20):[],
  ['all','spaces'].includes(kind)?db.select({id:spaces.id,label:spaces.name,sub:spaces.slug}).from(spaces).where(and(ilike(spaces.name,pattern),or(eq(spaces.visibility,'public'),inArray(spaces.id,db.select({id:members.spaceId}).from(members).where(eq(members.userId,user.id)))))).limit(20):[],
  ['all','clans'].includes(kind)?db.select({id:clans.id,label:clans.name,sub:clans.tag}).from(clans).where(or(ilike(clans.name,pattern),ilike(clans.tag,pattern))).limit(20):[],
  messageKind?db.select({id:messages.id,label:messages.content,at:messages.createdAt,authorId:messages.authorId,contextId:channels.id,spaceId:channels.spaceId,contextName:channels.name}).from(messages).innerJoin(channels,eq(channels.id,messages.channelId)).innerJoin(members,and(eq(members.spaceId,channels.spaceId),eq(members.userId,user.id))).where(and(isNull(messages.deletedAt),or(ilike(messages.content,pattern),filesOnly?fileMatch:undefined),filesOnly?fileMatch:undefined,author?eq(messages.authorId,author):undefined,channel?eq(channels.id,channel):undefined,date?gte(messages.createdAt,date):undefined)).orderBy(desc(messages.createdAt)).limit(120):[],
  messageKind?db.select({id:clanMessages.id,label:clanMessages.content,at:clanMessages.createdAt,authorId:clanMessages.authorId,contextId:clans.id,contextName:clans.name}).from(clanMessages).innerJoin(clans,eq(clans.id,clanMessages.clanId)).innerJoin(clanMembers,and(eq(clanMembers.clanId,clans.id),eq(clanMembers.userId,user.id))).where(and(isNull(clanMessages.deletedAt),or(ilike(clanMessages.content,pattern),filesOnly?clanFileMatch:undefined),filesOnly?clanFileMatch:undefined,author?eq(clanMessages.authorId,author):undefined,!channel||channel==='clan'?undefined:sql`false`,date?gte(clanMessages.createdAt,date):undefined)).orderBy(desc(clanMessages.createdAt)).limit(30):[],
  messageKind?db.select({id:directMessages.id,label:directMessages.text,at:directMessages.createdAt,authorId:directMessages.senderId,contextId:directMessages.conversationId}).from(directMessages).innerJoin(directConversationMembers,and(eq(directConversationMembers.conversationId,directMessages.conversationId),eq(directConversationMembers.userId,user.id))).where(and(isNull(directMessages.deletedAt),ilike(directMessages.text,pattern),filesOnly?ilike(directMessages.text,`${DIRECT_MESSAGE_ENVELOPE_PREFIX}%`):undefined,author?eq(directMessages.senderId,author):undefined,channel?eq(directMessages.conversationId,channel):undefined,date?gte(directMessages.createdAt,date):undefined)).orderBy(desc(directMessages.createdAt)).limit(30):[]
 ]);
 const allowed=await Promise.all(serverMessages.map(async row=>{const access=await getChannelPermissions(row.contextId,user.id);return hasPermission(access.permissions,Permission.ReadHistory)&&hasPermission(access.permissions,Permission.ViewChannels)?{type:'message',...row}:null}));const results=[...people.map(row=>({type:'person',...row})),...servers.map(row=>({type:'space',...row})),...clanRows.map(row=>({type:'clan',...row})),...allowed.filter(Boolean),...clanChat.map(row=>({type:'clan_message',...row})),...directChat.map(row=>({type:'direct_message',...row,label:decodeDirectMessage(row.label).text||decodeDirectMessage(row.label).attachments.map(item=>item.name).join(", ")}))];return NextResponse.json({results:results.slice(0,100)})}
