import { randomUUID } from "node:crypto";
import { and, eq, gt } from "drizzle-orm";
import { NextResponse } from "next/server";
import { getDatabase } from "@/db/client";
import { notifications, temporaryVoiceInvites, temporaryVoiceRooms } from "@/db/schema";
import { getCurrentUser } from "@/lib/auth";
import { eligible } from "@/lib/temporary-voice-access";
import { isTrustedMutationRequest } from "@/lib/security-controls";

export async function GET(request:Request){const user=await getCurrentUser();if(!user)return NextResponse.json({message:"Требуется вход."},{status:401});const url=new URL(request.url),type=url.searchParams.get("contextType")??"",id=url.searchParams.get("contextId")??"";if(!await eligible(type,id,user.id))return NextResponse.json({message:"Нет доступа."},{status:403});const rooms=await getDatabase().select().from(temporaryVoiceRooms).where(and(eq(temporaryVoiceRooms.contextType,type),eq(temporaryVoiceRooms.contextId,id),gt(temporaryVoiceRooms.expiresAt,new Date()))).limit(15);return NextResponse.json({rooms})}
export async function POST(request:Request){if(!isTrustedMutationRequest(request))return NextResponse.json({message:"Запрос отклонён."},{status:403});const user=await getCurrentUser();if(!user)return NextResponse.json({message:"Требуется вход."},{status:401});const body=await request.json().catch(()=>({})),type=body.contextType,id=body.contextId,target=body.inviteUserId;if(!["direct","clan"].includes(type)||typeof id!=="string"||!await eligible(type,id,user.id))return NextResponse.json({message:"Нет доступа к разговору."},{status:403});if(type==="direct"&&(!target||!await eligible(type,id,target)))return NextResponse.json({message:"Участник диалога не найден."},{status:400});if(target&&(!await eligible(type,id,target)||target===user.id))return NextResponse.json({message:"Приглашённый пользователь недоступен."},{status:400});const db=getDatabase(),roomId=randomUUID();const room=await db.transaction(async tx=>{const [created]=await tx.insert(temporaryVoiceRooms).values({id:roomId,creatorId:user.id,contextType:type,contextId:id,expiresAt:new Date(Date.now()+2*3600_000)}).returning();if(target){await tx.insert(temporaryVoiceInvites).values({roomId,userId:target});await tx.insert(notifications).values({id:randomUUID(),userId:target,actorId:user.id,type:"temporary_voice_invite",title:"Приглашение в голосовую комнату",body:"Присоединитесь к разговору в течение двух часов.",entityType:"temporary_voice",entityId:roomId})}return created});return NextResponse.json({room},{status:201})}
