"use client";
import { type FormEvent, useEffect, useState } from "react";
import { LoaderCircle, Palette, Trash2 } from "lucide-react";

type Theme={id:string;label:string;access:string;surface:string;panel:string;deep:string;raised:string;accent:string;text:string;muted:string;custom?:boolean};
const defaults={id:"",label:"",access:"free",surface:"#101622",panel:"#171d2b",deep:"#080d18",raised:"#222a3b",accent:"#8f70ff",text:"#f5f6ff",muted:"#a1a8bd"};

export function AdminThemesPanel(){
 const [themes,setThemes]=useState<Theme[]>([]),[draft,setDraft]=useState(defaults),[busy,setBusy]=useState(false),[notice,setNotice]=useState("");
 async function load(){const r=await fetch("/api/admin/themes",{cache:"no-store"});const d=await r.json();if(r.ok)setThemes(d.themes??[]);else setNotice(d.message??"Не удалось загрузить темы.")}
 useEffect(()=>{void load()},[]);
 async function submit(event:FormEvent){event.preventDefault();setBusy(true);setNotice("");try{const r=await fetch("/api/admin/themes",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(draft)}),d=await r.json();setNotice(r.ok?"Тема сохранена и доступна в «Внешний вид».":d.message??"Не удалось сохранить тему.");if(r.ok){setDraft(defaults);await load()}}finally{setBusy(false)}}
 async function remove(id:string){if(!window.confirm("Удалить пользовательскую тему? У пользователей с этой темой останется сохранённый id до следующего выбора."))return;const r=await fetch("/api/admin/themes",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({id})});const d=await r.json();setNotice(r.ok?"Тема удалена.":d.message??"Не удалось удалить.");if(r.ok)await load()}
 return <div className="admin-themes-panel"><header><div><Palette size={20}/><strong>Темы интерфейса</strong></div><p>Добавленная тема появляется в Настройки → Внешний вид. Цвета применяются ко всему интерфейсу через CSS-переменные.</p></header>
 <div className="admin-theme-list">{themes.map(theme=><article key={theme.id}><span className="admin-theme-swatch" style={{background:theme.surface,borderColor:theme.accent}}><i style={{background:theme.deep}}/><i style={{background:theme.panel}}/><i style={{background:theme.raised}}/></span><div><strong>{theme.label}</strong><small>{theme.id} · {theme.access}</small></div>{theme.custom?<button onClick={()=>void remove(theme.id)} aria-label={`Удалить тему ${theme.label}`}><Trash2 size={15}/></button>:<em>встроенная</em>}</article>)}</div>
 <form className="admin-theme-form" onSubmit={submit}><h3>Загрузить / обновить тему</h3><div className="form-grid"><label>ID<input value={draft.id} onChange={e=>setDraft({...draft,id:e.target.value.toLowerCase()})} placeholder="my-theme" required/></label><label>Название<input value={draft.label} onChange={e=>setDraft({...draft,label:e.target.value})} placeholder="Моя тема" required/></label></div><label>Доступ<select value={draft.access} onChange={e=>setDraft({...draft,access:e.target.value})}><option value="free">Всем</option><option value="superflip">SuperFlip</option></select></label><div className="admin-theme-colors">{(["surface","panel","deep","raised","accent","text","muted"] as const).map(key=><label key={key}><span>{key}</span><input type="color" value={draft[key]} onChange={e=>setDraft({...draft,[key]:e.target.value})}/><input value={draft[key]} onChange={e=>setDraft({...draft,[key]:e.target.value})} pattern="#[0-9a-fA-F]{6}" required/></label>)}</div><p className="admin-theme-help">Инструкция: surface — фон приложения, panel — сайдбары, deep — самые тёмные области, raised — карточки/кнопки, accent — акцент, text/muted — основной и вторичный текст. После сохранения откройте «Внешний вид» и проверьте тему в live preview на desktop и mobile.</p><button className="account-primary" disabled={busy}>{busy?<><LoaderCircle className="spin" size={16}/>Сохраняем…</>:"Сохранить тему"}</button>{notice?<p role="status">{notice}</p>:null}</form>
 </div>
}
