"use client";
import { useEffect, useState } from "react";
import { Activity, Crown, Download, LoaderCircle, MessageCircle, Server, ShieldCheck, Users, X } from "lucide-react";
type User = { id: string; email: string; username: string; displayName: string; platformRole: "user" | "admin"; bannedAt: string | null };

export function AdminDialog({ onClose, embedded = false }: { onClose?: () => void; embedded?: boolean }) {
  const [data, setData] = useState<{ users: User[]; superflip: unknown[]; auditLogs: unknown[]; moderationFlags: unknown[]; directMessages: unknown[] } | null>(null); const [notice, setNotice] = useState("");
  async function load() { const response = await fetch("/api/admin/dashboard"); if (response.ok) setData(await response.json()); }
  useEffect(() => { void (async () => { const response = await fetch("/api/admin/dashboard"); if (response.ok) setData(await response.json()); })(); }, []);
  async function userAction(userId: string, action: string, extra: Record<string, unknown> = {}) { const response = await fetch("/api/admin/dashboard", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ userId, action, ...extra }) }); const result = await response.json(); setNotice(response.ok ? result.temporaryPassword ? `Временный пароль: ${result.temporaryPassword}` : "Изменение сохранено." : result.message); await load(); }
  async function grant(userId: string) { const reason = window.prompt("Причина выдачи SuperFlip:", "Подарок администратора"); if (!reason) return; const response = await fetch("/api/admin/superflip/grant", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ userId, reason, months: 1 }) }); const result = await response.json(); setNotice(response.ok ? "SuperFlip выдан на 1 месяц." : result.message); await load(); }
  async function revoke(userId: string) { await fetch("/api/admin/superflip/grant", { method: "DELETE", headers: { "content-type": "application/json" }, body: JSON.stringify({ userId }) }); setNotice("SuperFlip отозван."); await load(); }
  const content = <section className={`admin-dialog ${embedded ? "admin-dialog-embedded" : ""}`}><header><span><ShieldCheck size={22} /></span><div><small>УПРАВЛЕНИЕ ПЛАТФОРМОЙ</small><h2>Админ-панель</h2></div>{onClose ? <button onClick={onClose}><X size={19} /></button> : null}</header>{notice ? <p className="admin-notice">{notice}</p> : null}{!data ? <div className="social-loading"><LoaderCircle className="spin" /> Загрузка…</div> : <><div className="admin-toolbar"><p>Управляй сообществом. Развивай. Контролируй.</p><button onClick={()=>window.print()}><Download size={14}/> Скачать отчёт</button></div><div className="admin-stats"><span><Users/><small>Пользователи</small><b>{data.users.length.toLocaleString("ru-RU")}</b><i>↑ активность</i></span><span><Server/><small>SuperFlip</small><b>{data.superflip.length}</b><i>подписок</i></span><span><ShieldCheck/><small>Модерация</small><b>{data.moderationFlags.length}</b><i>флагов</i></span><span><MessageCircle/><small>Сообщения</small><b>{data.directMessages.length}</b><i>в журнале</i></span></div><div className="admin-dashboard-grid"><section><h3>Активность пользователей</h3><div className="admin-bars">{Array.from({length:18},(_,i)=><i key={i} style={{height:`${28+((i*17)%58)}%`}} />)}</div></section><section><h3>Статус системы</h3><p><Activity size={15}/> API <b>Работает</b></p><p><Activity size={15}/> База данных <b>Работает</b></p><p><Activity size={15}/> Голосовые серверы <b>Работает</b></p></section></div><div className="admin-users"><h3>Все пользователи FlipZero</h3>{data.users.map((user) => <article key={user.id}><div><strong>{user.displayName}</strong><span>@{user.username} · {user.email}</span></div><em className={user.platformRole}>{user.platformRole}</em><button onClick={() => grant(user.id)}><Crown size={13} /> Выдать</button><button onClick={() => revoke(user.id)}>Отозвать</button><button onClick={() => userAction(user.id, "role", { role: user.platformRole === "admin" ? "user" : "admin" })}>Роль</button><button onClick={() => userAction(user.id, user.bannedAt ? "unban" : "ban")}>{user.bannedAt ? "Разбан" : "Бан"}</button><button onClick={() => userAction(user.id, "reset_password")}>Сброс пароля</button></article>)}</div><div className="admin-log-summary"><h3>Аудит и модерация</h3><p>Действий администраторов: {data.auditLogs.length}. Флагов модерации: {data.moderationFlags.length}. Последние личные сообщения доступны для рассмотрения жалоб.</p></div></>}</section>;
  return embedded ? content : <div className="dialog-backdrop" onMouseDown={(e) => e.target === e.currentTarget && onClose?.()}>{content}</div>;
}
