"use client";
import { useCallback, useEffect, useState } from "react";
import { Gamepad2, Hourglass, Trophy } from "lucide-react";
type Game={id:string;kind:string;prompt:string;options:string[];expiresAt:string;creatorId:string;winnerId:string|null;done:boolean;plays:Array<{userId:string;displayName:string;answer?:string;correct?:boolean}>};
export const gameMarker=(text:string)=>/^\[game:([0-9a-f-]{36})\]$/i.exec(text.trim())?.[1]??null;
export async function createChatGame(scope:"channel"|"clan"|"direct",scopeId:string,command:string){const kind=command==="/quiz"?"trivia":command==="/duel"?"duel":"guess";const response=await fetch("/api/v1/chat-games",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({scope,scopeId,kind})}),data=await response.json();if(!response.ok)throw Error(data.message??"Не удалось создать игру.");return `[game:${data.game.id}]`}
export function ChatGameCard({id,currentUserId}:{id:string;currentUserId:string}){
 const [game,setGame]=useState<Game|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[time,setTime]=useState(0);
 const load=useCallback(async()=>{try{const response=await fetch(`/api/v1/chat-games/${id}`,{cache:"no-store"}),data=await response.json();if(!response.ok)throw Error(data.message??"Игра недоступна.");setGame(data.game)}catch(reason){setError(reason instanceof Error?reason.message:"Ошибка загрузки.")}},[id]);
 useEffect(()=>{const start=window.setTimeout(()=>void load(),0),timer=window.setInterval(()=>{setTime(Date.now());void load()},4000);return()=>{window.clearTimeout(start);window.clearInterval(timer)}},[load]);
 async function play(answer:string){setBusy(true);setError("");try{const response=await fetch(`/api/v1/chat-games/${id}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({answer})}),data=await response.json();if(!response.ok)throw Error(data.message??"Не удалось сделать ход.");await load()}catch(reason){setError(reason instanceof Error?reason.message:"Ход не выполнен.")}finally{setBusy(false)}}
 const remaining=game?Math.max(0,Math.ceil((new Date(game.expiresAt).getTime()-time)/1000)):0;
 return <section className="chat-game-card" aria-label="Мини-игра"><header><Gamepad2 size={17}/><strong>{game?.kind==="duel"?"Дуэль":game?.kind==="guess"?"Угадай автора":"Викторина"}</strong>{game?.done?<Trophy size={16}/>:<small><Hourglass size={13}/>{remaining} сек.</small>}</header>{error?<p role="alert">{error}</p>:null}{game?<><p>{game.prompt}</p><div>{game.options.map(option=><button type="button" key={option} disabled={busy||game.done||game.plays.some(play=>play.userId===currentUserId)||remaining<=0} onClick={()=>void play(option)}>{option}</button>)}</div><footer>{game.winnerId?`Победил ${game.plays.find(play=>play.userId===game.winnerId)?.displayName??"участник"}`:game.done?"Игра завершена":game.plays.some(play=>play.userId===currentUserId)?"Ход принят. Ждём остальных.":"Выберите ответ"}</footer></>:<p>Загружаем игру…</p>}</section>
}
