"use client";

import { useEffect, useMemo, useState } from "react";
import { Award, Crown, LoaderCircle, Medal, Palette, Plus, Sparkles, Trophy, X } from "lucide-react";
import { useModalA11y } from "@/hooks/use-modal-a11y";

type Progress = { level: number; current: number; required: number; percent: number };
type Cosmetics = { title: string; avatarFrame: string; profileEffect: string; showcasedPath: string };
type GamificationData = {
  profile: { id: string; displayName: string; username: string; globalLevel: number; global: Progress; local: Progress; cosmetics: Cosmetics };
  paths: Array<Progress & { path: string; label: string; icon: string; description: string; xp: number }>;
  achievements: Array<{ id: string; name: string; description: string; icon: string; rarity: string; target: number; progress: number; unlockedAt: string | null; isShowcased: boolean }>;
  leaderboard: Array<{ userId: string; displayName: string; username: string; xp: number; level: number; rank: number; isCurrentUser: boolean }>;
};

export function GamificationDialog({spaceId, isOwner, onClose }: { spaceId: string; isOwner: boolean; onClose: () => void }) {
  const dialogRef = useModalA11y(onClose);
  const [data, setData] = useState<GamificationData | null>(null);
  const [tab, setTab] = useState<"profile" | "achievements" | "leaderboard" | "create">("profile");
  const [error, setError] = useState("");
  const [saving, setSaving] = useState(false);
  async function load() { const response = await fetch(`/api/v1/gamification?spaceId=${spaceId}`); const result = await response.json(); if (!response.ok) setError(result.message ?? "Не удалось загрузить прогресс."); else setData(result); }
  useEffect(() => { let cancelled = false; fetch(`/api/v1/gamification?spaceId=${spaceId}`).then((response) => response.json().then((result) => ({ response, result }))).then(({ response, result }) => { if (cancelled) return; if (!response.ok) setError(result.message ?? "Не удалось загрузить прогресс."); else setData(result); }); return () => { cancelled = true; }; }, [spaceId]);
  const showcased = useMemo(() => data?.achievements.filter((item) => item.isShowcased) ?? [], [data]);
  async function toggleShowcase(achievementId: string) { setError(""); const response = await fetch("/api/v1/gamification", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ achievementId }) }); const result = await response.json(); if (!response.ok) setError(result.message ?? "Не удалось изменить витрину."); else await load(); }
  async function saveCosmetics(form: FormData) { setSaving(true); setError(""); const response = await fetch("/api/v1/gamification", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify(Object.fromEntries(form.entries())) }); const result = await response.json(); setSaving(false); if (!response.ok) setError(result.message ?? "Не удалось сохранить оформление."); else await load(); }
  async function createAchievement(form: FormData) { setSaving(true); setError(""); const response = await fetch(`/api/v1/spaces/${spaceId}/achievements`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(Object.fromEntries(form.entries())) }); const result = await response.json(); setSaving(false); if (!response.ok) setError(result.message ?? "Не удалось создать достижение."); else { await load(); setTab("achievements"); } }

  return <div className="dialog-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><section ref={dialogRef} tabIndex={-1} className="space-dialog gamification-dialog" role="dialog" aria-modal="true" aria-label="Прогресс и достижения">
    <button className="dialog-close" onClick={onClose} aria-label="Закрыть"><X size={18} /></button>
    <div className="gamification-head"><span className="dialog-symbol"><Trophy size={22} /></span><div><h2>Прогресс FlipZero</h2><p>Уровни, пути развития и достижения</p></div></div>
    <nav className="gamification-tabs"><button className={tab === "profile" ? "active" : ""} onClick={() => setTab("profile")}><Sparkles size={15} /> Профиль</button><button className={tab === "achievements" ? "active" : ""} onClick={() => setTab("achievements")}><Award size={15} /> Достижения</button><button className={tab === "leaderboard" ? "active" : ""} onClick={() => setTab("leaderboard")}><Crown size={15} /> Рейтинг</button>{isOwner ? <button className={tab === "create" ? "active" : ""} onClick={() => setTab("create")}><Plus size={15} /> Создать</button> : null}</nav>
    {error ? <div className="auth-error">{error}</div> : null}
    {!data ? <div className="gamification-loading"><LoaderCircle className="spin" /> Загружаем прогресс...</div> : <div className="gamification-content">
      {tab === "profile" ? <div className="progress-dashboard"><article className={`hero-profile effect-${data.profile.cosmetics.profileEffect}`}><div className={`hero-avatar frame-${data.profile.cosmetics.avatarFrame}`}>{data.profile.displayName.split(/\s+/).map((part) => part[0]).join("").slice(0, 2)}</div><div><small>{data.profile.cosmetics.title}</small><h3>{data.profile.displayName}</h3><span>@{data.profile.username}</span></div><b>LVL {data.profile.globalLevel}</b></article><div className="dual-levels"><LevelCard label="Глобальный уровень" progress={data.profile.global} /><LevelCard label="В этом сообществе" progress={data.profile.local} /></div><h3 className="section-label">Пути развития</h3><div className="path-grid">{data.paths.map((path) => <article key={path.path}><i>{path.icon}</i><div><strong>{path.label}</strong><span>{path.description}</span><div className="mini-progress"><b style={{ width: `${path.percent}%` }} /></div></div><em>{path.level}</em></article>)}</div><h3 className="section-label">Витрина достижений</h3><div className="showcase-row">{showcased.length ? showcased.map((item) => <span key={item.id} title={item.name}>{item.icon}<small>{item.name}</small></span>) : <p>Закрепите разблокированные достижения на витрине.</p>}</div><form className="cosmetic-form" action={saveCosmetics}><label><span>Титул</span><select name="title" defaultValue={data.profile.cosmetics.title}><option>Путешественник</option><option>Голос сообщества</option><option>Создатель атмосферы</option><option>Легенда FlipZero</option></select></label><label><span>Рамка</span><select name="avatarFrame" defaultValue={data.profile.cosmetics.avatarFrame}><option value="coral">Коралл</option><option value="violet">Фиолет</option><option value="lime">Лайм</option><option value="sky">Небо</option></select></label><label><span>Эффект</span><select name="profileEffect" defaultValue={data.profile.cosmetics.profileEffect}><option value="glow">Свечение</option><option value="waves">Волны</option><option value="none">Без эффекта</option></select></label><label><span>Главный путь</span><select name="showcasedPath" defaultValue={data.profile.cosmetics.showcasedPath}>{data.paths.map((path) => <option key={path.path} value={path.path}>{path.label}</option>)}</select></label><button className="auth-submit" disabled={saving}><Palette size={15} /> Сохранить стиль</button></form></div> : null}
      {tab === "achievements" ? <div className="achievement-grid">{data.achievements.map((item) => { const unlocked = Boolean(item.unlockedAt); const percent = Math.min(100, Math.round((item.progress / item.target) * 100)); return <article className={`${unlocked ? "unlocked" : "locked"} rarity-${item.rarity}`} key={item.id}><i>{item.icon}</i><div><small>{item.rarity}</small><strong>{item.name}</strong><span>{item.description}</span><div className="achievement-progress"><b style={{ width: `${percent}%` }} /></div><em>{item.progress} / {item.target}</em></div>{unlocked ? <button onClick={() => toggleShowcase(item.id)}>{item.isShowcased ? "Убрать" : "На витрину"}</button> : null}</article>; })}</div> : null}
      {tab === "leaderboard" ? <div className="leaderboard"><header><span>Место</span><span>Участник</span><span>Уровень</span><span>XP</span></header>{data.leaderboard.map((entry) => <article className={entry.isCurrentUser ? "current" : ""} key={entry.userId}><b>{entry.rank <= 3 ? <Medal size={17} /> : `#${entry.rank}`}</b><span><strong>{entry.displayName}</strong><small>@{entry.username}</small></span><em>{entry.level}</em><i>{entry.xp.toLocaleString("ru-RU")}</i></article>)}</div> : null}
      {tab === "create" && isOwner ? <form className="achievement-create" action={createAchievement}><label><span>Название</span><input name="name" required maxLength={50} placeholder="Например, Душа сообщества" /></label><label><span>Описание</span><textarea name="description" required maxLength={160} placeholder="Что нужно сделать участнику" /></label><div className="form-grid"><label><span>Событие</span><select name="eventSource"><option value="message">Сообщения</option><option value="reaction_received">Реакции</option><option value="voice_minute">Минуты в голосе</option><option value="event_hosted">Проведённые события</option><option value="invite_joined">Приглашённые участники</option><option value="level">Глобальный уровень</option></select></label><label><span>Цель</span><input name="target" type="number" min="1" max="100000" defaultValue="10" required /></label><label><span>Редкость</span><select name="rarity"><option value="common">Обычная</option><option value="rare">Редкая</option><option value="epic">Эпическая</option><option value="legendary">Легендарная</option></select></label><label><span>Иконка</span><input name="icon" defaultValue="✦" maxLength={8} /></label></div><button className="auth-submit" disabled={saving}>{saving ? <LoaderCircle className="spin" size={16} /> : <Plus size={16} />} Создать достижение</button></form> : null}
    </div>}
  </section></div>;
}

function LevelCard({ label, progress }: { label: string; progress: Progress }) { return <article><div><span>{label}</span><b>Уровень {progress.level}</b></div><div className="level-progress"><i style={{ width: `${progress.percent}%` }} /></div><small>{progress.current.toLocaleString("ru-RU")} / {progress.required.toLocaleString("ru-RU")} XP</small></article>; }
