"use client";
import { useEffect, useRef, useState } from "react";
import { Search, X } from "lucide-react";
type Hit={type:string;id:string;label:string;sub?:string;spaceId?:string;contextId?:string;contextName?:string;at?:string};
export function GlobalSearch({onClose,onOpenPerson,onOpenDirect,onOpenChannel,onOpenSpace}:{onClose:()=>void;onOpenPerson:(id:string)=>void;onOpenDirect:(id:string)=>void;onOpenChannel:(spaceId:string,channelId:string)=>void;onOpenSpace:(id:string)=>void}){
 const [q,setQ]=useState(""),[kind,setKind]=useState("all"),[author,setAuthor]=useState(""),[channel,setChannel]=useState(""),[after,setAfter]=useState(""),[items,setItems]=useState<Hit[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState("");const input=useRef<HTMLInputElement>(null);
 useEffect(()=>{input.current?.focus();const key=(event:KeyboardEvent)=>{if(event.key==="Escape")onClose()};window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key)},[onClose]);
 useEffect(()=>{if(q.trim().length<2){const resetTimer=setTimeout(()=>setItems([]),0);return()=>clearTimeout(resetTimer)}const controller=new AbortController(),timer=setTimeout(async()=>{setLoading(true);try{const params=new URLSearchParams({q,kind});if(author)params.set("author",author);if(channel)params.set("channel",channel);if(after)params.set("after",after);const response=await fetch(`/api/v1/search?${params}`,{signal:controller.signal,cache:"no-store"});const data=await response.json();if(!response.ok)throw Error(data.message);setItems(data.results??[]);setError("")}catch(reason){if(!controller.signal.aborted)setError(reason instanceof Error?reason.message:"Ошибка поиска.")}finally{if(!controller.signal.aborted)setLoading(false)}},250);return()=>{controller.abort();clearTimeout(timer)}},[q,kind,author,channel,after]);
 function open(row:Hit){if(row.type==="person")onOpenPerson(row.id);else if(row.type==="space")onOpenSpace(row.id);else if(row.type==="clan")window.dispatchEvent(new CustomEvent("flipzero:open-clan",{detail:row.id}));else if(row.type==="message"&&row.spaceId&&row.contextId)onOpenChannel(row.spaceId,row.contextId);else if(row.type==="clan_message")window.dispatchEvent(new CustomEvent("flipzero:open-clan",{detail:row.contextId}));else if(row.type==="direct_message"&&row.contextId)onOpenDirect(row.contextId);onClose()}
 return <div className="global-search-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)onClose()}}><section className="global-search-panel" role="dialog" aria-modal="true" aria-label="Единый поиск"><header><Search size={20}/><input ref={input} value={q} onChange={event=>setQ(event.target.value)} placeholder="Сообщения, файлы, люди, серверы, кланы" aria-label="Поисковый запрос"/><button onClick={onClose} aria-label="Закрыть"><X/></button></header><div className="global-search-filters"><select value={kind} onChange={event=>setKind(event.target.value)} aria-label="Тип результата">{[["all","Всё"],["messages","Сообщения"],["files","Файлы"],["people","Люди"],["spaces","Пространства"],["clans","Кланы"]].map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><input value={author} onChange={event=>setAuthor(event.target.value)} placeholder="ID автора" aria-label="ID автора"/><input value={channel} onChange={event=>setChannel(event.target.value)} placeholder="ID канала" aria-label="ID канала"/><input type="date" value={after} onChange={event=>setAfter(event.target.value)} aria-label="Начиная с даты"/></div><div className="global-search-results" aria-live="polite">{loading?<p>Ищем…</p>:error?<p role="alert">{error}</p>:!q?<p>Начните вводить запрос. Быстрый вызов: Ctrl/⌘ + K.</p>:items.length?items.map((item,index)=><button key={item.type+item.id+index} onClick={()=>open(item)}><span>{({person:"Пользователь",space:"Пространство",clan:"Клан",message:"Сообщение",clan_message:"Клановый чат",direct_message:"Личное сообщение"} as Record<string,string>)[item.type]??item.type}</span><strong>{item.label}</strong><small>{item.sub??item.contextName??""}{item.at?` · ${new Date(item.at).toLocaleDateString("ru-RU")}`:""}</small></button>):<p>Совпадений нет.</p>}</div></section></div>
}
