"use client";
import { useCallback, useEffect, useState } from "react";
import { Bell, CheckCheck, MessageCircle, UserPlus, X } from "lucide-react";
type Item={id:string;type:string;title:string;body:string|null;entityType:string|null;entityId:string|null;readAt:string|null;createdAt:string;actor:{id:string;username:string;displayName:string;avatarUrl:string|null}|null};
export function NotificationCenter({onOpenMessages,onOpenFriends}:{onOpenMessages:(userId:string|null)=>void;onOpenFriends:()=>void}){
 const [open,setOpen]=useState(false),[items,setItems]=useState<Item[]>([]),[unread,setUnread]=useState(0);
 const load=useCallback(async()=>{const r=await fetch("/api/notifications",{cache:"no-store"});if(r.ok){const d=await r.json();setItems(d.notifications??[]);setUnread(d.unread??0)}},[]);
 useEffect(()=>{const first=window.setTimeout(()=>void load(),0);const t=window.setInterval(()=>void load(),15000);return()=>{window.clearTimeout(first);window.clearInterval(t)}},[load]);
 async function read(item:Item){if(!item.readAt)await fetch("/api/notifications",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:item.id})});setItems(v=>v.map(x=>x.id===item.id?{...x,readAt:new Date().toISOString()}:x));setUnread(v=>Math.max(0,v-(item.readAt?0:1)));setOpen(false);if(item.type==="friend_request")onOpenFriends();else if(item.type==="direct_message"||item.type==="friend_accepted")onOpenMessages(item.actor?.id??null)}
 async function readAll(){await fetch("/api/notifications",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({all:true})});setItems(v=>v.map(x=>({...x,readAt:x.readAt??new Date().toISOString()})));setUnread(0)}
 return <div className="notification-center"><button className={open?"is-active":""} aria-label="Уведомления" onClick={()=>setOpen(v=>!v)}><Bell size={19}/>{unread?<b className="notification-badge">{unread>99?"99+":unread}</b>:null}</button>{open?<section className="notification-popover"><header><div><small>FLIPZERO</small><h3>Уведомления</h3></div><button onClick={()=>setOpen(false)} aria-label="Закрыть"><X size={17}/></button></header>{unread?<button className="notification-read-all" onClick={()=>void readAll()}><CheckCheck size={15}/>Прочитать все</button>:null}<div className="notification-list">{items.length?items.map(item=><button key={item.id} className={item.readAt?"":"unread"} onClick={()=>void read(item)}><i>{item.type==="friend_request"||item.type==="friend_accepted"?<UserPlus size={17}/>:<MessageCircle size={17}/>}</i><span><strong>{item.title}</strong><small>{item.body}</small><time>{new Date(item.createdAt).toLocaleString("ru-RU",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"})}</time></span></button>):<p>Новых событий пока нет.</p>}</div></section>:null}</div>
}
