"use client";
import { useState } from "react";
import { ArrowRight, Check, Copy, Sparkles, UserRound, Users } from "lucide-react";
import { ImageUpload } from "./image-upload";

export function OnboardingWizard({ initialStep = 0, onComplete }: { initialStep?: number; onComplete: () => void }) {
  const [step, setStep] = useState(Math.min(3, initialStep) + 1); const [bio, setBio] = useState(""); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState("");
  async function advance(extra: Record<string, unknown> = {}) { setBusy(true); const response = await fetch("/api/v1/onboarding", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ step, ...extra }) }); setBusy(false); if (!response.ok) return; if (step === 4) onComplete(); else setStep((value) => value + 1); }
  async function share() { const url = `${location.origin}/register`; if (navigator.share) { try { await navigator.share({ title: "FlipZero", text: "Присоединяйся ко мне в FlipZero", url }); return; } catch {} } await navigator.clipboard.writeText(url); setNotice("Ссылка скопирована"); }
  return <div className="dialog-backdrop onboarding-backdrop"><section className="onboarding-wizard" role="dialog" aria-modal="true" aria-labelledby="onboarding-title"><div className="onboarding-progress"><span style={{ width: `${step * 25}%` }} /></div><small>ШАГ {step} ИЗ 4 · +50 XP</small>{step === 1 ? <><UserRound size={38} /><h2 id="onboarding-title">Добавьте аватар</h2><p>Обрежьте своё фото или продолжите с текущей иконкой.</p><ImageUpload kind="avatar" label="Выбрать фото" onUploaded={() => setNotice("Аватар сохранён")} /></> : step === 2 ? <><Sparkles size={38} /><h2 id="onboarding-title">Расскажите о себе</h2><p>Короткое описание поможет найти единомышленников.</p><textarea value={bio} onChange={(event) => setBio(event.target.value)} maxLength={190} placeholder="Например: люблю дизайн, игры и музыку" /></> : step === 3 ? <><Users size={38} /><h2 id="onboarding-title">FlipZero HQ</h2><p>Вступите в демонстрационное сообщество и познакомьтесь с возможностями платформы.</p><button className="onboarding-secondary" onClick={() => void advance({ joinDemo: true })} disabled={busy}>Вступить и продолжить</button></> : <><Copy size={38} /><h2 id="onboarding-title">Пригласите друга</h2><p>FlipZero интереснее вместе. Поделитесь персональной ссылкой или завершите знакомство.</p><button className="onboarding-secondary" onClick={() => void share()}>{notice || "Скопировать ссылку"}</button></>}<footer><button onClick={() => void advance(step === 2 ? { bio } : {})} disabled={busy}>{step === 4 ? <><Check size={17} /> Завершить</> : <>Пропустить <ArrowRight size={17} /></>}</button></footer></section></div>;
}
