"use client";
import { useCallback, useEffect, useState } from "react";
import { Coins, Gift, LoaderCircle, ShoppingBag, Star, Trophy } from "lucide-react";

type Ledger={id:string;amount:number;reason:string;createdAt:string};
type Quest={key:string;title:string;description:string;period:"daily"|"weekly";target:number;progress:number;coins:number;xp:number;claimed:boolean};
type Item={id:string;title:string;description:string;category:string;rarity:string;price:number;preview:string;superflipOnly:boolean};
export function PersonalEconomy(){
  const [tab,setTab]=useState<"quests"|"shop"|"history">("quests");
  const [balance,setBalance]=useState(0);const [ledger,setLedger]=useState<Ledger[]>([]);const [quests,setQuests]=useState<Quest[]>([]);const [streak,setStreak]=useState(0);
  const [items,setItems]=useState<Item[]>([]);const [inventory,setInventory]=useState<string[]>([]);const [equipped,setEquipped]=useState<string[]>([]);const [busy,setBusy]=useState("");const [error,setError]=useState("");const [loading,setLoading]=useState(true);
  const refresh=useCallback(async()=>{try{const responses=await Promise.all([fetch("/api/v1/economy",{cache:"no-store"}),fetch("/api/v1/quests",{cache:"no-store"}),fetch("/api/v1/shop",{cache:"no-store"})]);if(responses.some(r=>!r.ok))throw Error("Не удалось загрузить данные.");const [economy,questData,shop]=await Promise.all(responses.map(r=>r.json()));setBalance(economy.balance);setLedger(economy.transactions);setQuests(questData.quests);setStreak(questData.streak);setItems(shop.items);setInventory(shop.inventory.map((row:{itemId:string})=>row.itemId));setEquipped(shop.equipped.map((row:{itemId:string})=>row.itemId));setError("")}catch{setError("Не удалось загрузить данные. Повторите попытку.")}finally{setLoading(false)}},[]);
  useEffect(()=>{const timer=window.setTimeout(()=>void refresh(),0);return()=>window.clearTimeout(timer)},[refresh]);
  async function act(path:string,body:object,id:string){setBusy(id);setError("");try{const response=await fetch(path,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw Error(data.message??"Действие не выполнено.");await refresh()}catch(reason){setError(reason instanceof Error?reason.message:"Действие не выполнено.")}finally{setBusy("")}}
  return <div className="personal-economy"><header><div><small>МОЁ ПРОСТРАНСТВО</small><h3>Монеты и открытия</h3><p>Зарабатывайте за реальные действия и меняйте облик профиля.</p></div><strong><Coins size={23}/>{balance.toLocaleString("ru-RU")}</strong></header><nav aria-label="Экономика"><button className={tab==="quests"?"active":""} onClick={()=>setTab("quests")}><Trophy size={17}/>Квесты</button><button className={tab==="shop"?"active":""} onClick={()=>setTab("shop")}><ShoppingBag size={17}/>Магазин</button><button className={tab==="history"?"active":""} onClick={()=>setTab("history")}><Coins size={17}/>История</button></nav>{error?<div role="alert" className="auth-error">{error}<button onClick={()=>void refresh()}>Повторить</button></div>:null}{loading?<div className="social-loading"><LoaderCircle className="spin"/>Загружаем…</div>:tab==="quests"?<><div className="personal-streak"><Gift size={22}/><span><strong>Серия: {streak} дн.</strong><small>Забирайте ежедневную награду, чтобы поддерживать серию.</small></span></div><div className="personal-economy-grid">{quests.map(quest=><article key={quest.key}><small>{quest.period==="daily"?"ЕЖЕДНЕВНЫЙ":"ЕЖЕНЕДЕЛЬНЫЙ"}</small><strong>{quest.title}</strong><p>{quest.description}</p><div className="personal-progress" role="progressbar" aria-valuenow={quest.progress} aria-valuemin={0} aria-valuemax={quest.target} aria-label={quest.title}><i style={{width:`${Math.min(100,100*quest.progress/quest.target)}%`}}/></div><span>{quest.progress}/{quest.target} · {quest.xp} XP · {quest.coins} монет</span><button disabled={quest.claimed||quest.progress<quest.target||!!busy} onClick={()=>void act("/api/v1/quests",{questKey:quest.key},quest.key)}>{quest.claimed?"Получено":busy===quest.key?"Забираем…":"Забрать"}</button></article>)}</div></>:tab==="shop"?<div className="personal-economy-grid">{items.map(item=><article key={item.id} className={`cosmetic-preview cosmetic-${item.preview}`}><small>{item.rarity.toUpperCase()} · {item.category}</small><span className="cosmetic-preview-symbol"><Star size={25}/></span><strong>{item.title}</strong><p>{item.description}</p><span>{item.superflipOnly?"Для SuperFlip · ":""}{item.price} монет</span><button disabled={!!busy||equipped.includes(item.id)} onClick={()=>{if(!inventory.includes(item.id)&&!window.confirm(`Купить «${item.title}» за ${item.price} монет?`))return;void act("/api/v1/shop",{action:inventory.includes(item.id)?"equip":"purchase",itemId:item.id},item.id)}}>{equipped.includes(item.id)?"Надето":inventory.includes(item.id)?"Надеть":"Купить"}</button></article>)}</div>:<div className="personal-ledger">{ledger.length?ledger.map(entry=><article key={entry.id}><span><strong>{entry.reason}</strong><small>{new Date(entry.createdAt).toLocaleString("ru-RU")}</small></span><b className={entry.amount>0?"positive":""}>{entry.amount>0?"+":""}{entry.amount}</b></article>):<p>Операций пока нет. Выполните первый квест.</p>}</div>}</div>
}
