"use client";
import { useEffect, useState } from "react";
type Pref={theme:string;accentColor:string;dndEnabled:boolean;dndDays:number[];dndStart:string;dndEnd:string;dndTimezone:string;dndFavoriteIds:string[];dndClanException:boolean};
type Theme={id:string;label:string;access:string;surface:string;accent:string};
export function PersonalizationSettings({kind}:{kind:"appearance"|"notifications"}){const [value,setValue]=useState<Pref|null>(null),[themes,setThemes]=useState<Theme[]>([]),[error,setError]=useState(""),[saved,setSaved]=useState(""),[busy,setBusy]=useState(false),[favorites,setFavorites]=useState<Array<{id:string;displayName:string}>>([]);
 useEffect(()=>{void fetch("/api/v1/preferences",{cache:"no-store"}).then(r=>r.json()).then(data=>{setValue(data.preferences);setThemes(data.themes??[])}).catch(()=>setError("Не удалось загрузить настройки."));if(kind==="notifications")void fetch("/api/friends").then(r=>r.json()).then(data=>setFavorites(data.friends??[])).catch(()=>undefined)},[kind]);
 async function save(){if(!value)return;setBusy(true);setError("");setSaved("");try{const response=await fetch("/api/v1/preferences",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(value)}),data=await response.json();if(!response.ok)throw Error(data.message);setValue(data.preferences);setSaved("Сохранено в аккаунте.");window.dispatchEvent(new Event("flipzero:preferences-updated"))}catch(reason){setError(reason instanceof Error?reason.message:"Ошибка сохранения.")}finally{setBusy(false)}}
 if(!value)return <p>Загружаем настройки…</p>;
 return <section className="personalization-settings">{kind==="appearance"?<><h3>Тема и акцент</h3><div className="theme-choices">{themes.map(theme=><button key={theme.id} className={value.theme===theme.id?"active":""} onClick={()=>setValue({...value,theme:theme.id,accentColor:theme.accent})}><i style={{background:theme.surface,borderColor:theme.accent}}/><strong>{theme.label}</strong><small>{theme.access==="free"?"Доступна всем":theme.access==="superflip"?"SuperFlip":"Магазин"}</small></button>)}</div><label>Акцентный цвет <input type="color" value={/^#[0-9a-fA-F]{6}$/.test(value.accentColor)?value.accentColor:"#8f70ff"} onChange={event=>setValue({...value,accentColor:event.target.value})}/><input aria-label="HEX цвета" value={value.accentColor} onChange={event=>setValue({...value,accentColor:event.target.value})}/></label></>:<><h3>Тихие часы</h3><label><input type="checkbox" checked={value.dndEnabled} onChange={event=>setValue({...value,dndEnabled:event.target.checked})}/> Не беспокоить по расписанию</label><div className="personalization-days">{["Вс","Пн","Вт","Ср","Чт","Пт","Сб"].map((label,index)=><button key={label} className={value.dndDays.includes(index)?"active":""} aria-pressed={value.dndDays.includes(index)} onClick={()=>setValue({...value,dndDays:value.dndDays.includes(index)?value.dndDays.filter(day=>day!==index):[...value.dndDays,index]})}>{label}</button>)}</div><div className="personalization-times"><label>С <input type="time" value={value.dndStart} onChange={event=>setValue({...value,dndStart:event.target.value})}/></label><label>До <input type="time" value={value.dndEnd} onChange={event=>setValue({...value,dndEnd:event.target.value})}/></label><label>Часовой пояс <input value={value.dndTimezone} onChange={event=>setValue({...value,dndTimezone:event.target.value})} placeholder="Europe/Moscow"/></label></div><label><input type="checkbox" checked={value.dndClanException} onChange={event=>setValue({...value,dndClanException:event.target.checked})}/> Разрешить уведомления клана</label><strong>Избранные друзья</strong><div className="personalization-favorites">{favorites.length?favorites.map(friend=><label key={friend.id}><input type="checkbox" checked={value.dndFavoriteIds.includes(friend.id)} onChange={event=>setValue({...value,dndFavoriteIds:event.target.checked?[...value.dndFavoriteIds,friend.id]:value.dndFavoriteIds.filter(id=>id!==friend.id)})}/>{friend.displayName}</label>):<small>Добавьте друзей, чтобы выбрать исключения.</small>}</div></>}{error?<p role="alert">{error}</p>:null}{saved?<p role="status">{saved}</p>:null}<button className="account-primary" disabled={busy} onClick={()=>void save()}>{busy?"Сохраняем…":"Сохранить настройки"}</button></section>
}
