"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import { ImagePlus, Plus, X } from "lucide-react";

type Story={id:string;userId:string;name:string;avatarUrl:string|null;content:string;imageUrl:string|null;emoji:string|null;audience:string;createdAt:string;expiresAt:string;viewed:boolean;viewCount?:number;reactions:{userId:string;emoji:string}[]};
export function StoryStrip({userId}:{userId:string}){
 const [stories,setStories]=useState<Story[]>([]),[selected,setSelected]=useState<Story|null>(null),[compose,setCompose]=useState(false),[content,setContent]=useState(""),[emoji,setEmoji]=useState(""),[audience,setAudience]=useState("friends"),[hidden,setHidden]=useState(""),[image,setImage]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");const uploadRef=useRef<HTMLInputElement>(null);
 const refresh=useCallback(async()=>{const response=await fetch("/api/v1/stories",{cache:"no-store"});if(response.ok)setStories((await response.json()).stories??[])},[]);
 useEffect(()=>{void refresh()},[refresh]);
 useEffect(()=>{if(!selected)return;const key=(event:KeyboardEvent)=>{if(event.key==="Escape")setSelected(null)};window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key)},[selected]);
 async function upload(file:File){setBusy(true);setError("");try{const form=new FormData();form.set("kind","story");form.set("file",file);const response=await fetch("/api/v1/media",{method:"POST",body:form});const data=await response.json();if(!response.ok)throw Error(data.message);setImage(data.story.url)}catch(reason){setError(reason instanceof Error?reason.message:"Ошибка загрузки.")}finally{setBusy(false)}}
 async function create(){setBusy(true);setError("");try{const response=await fetch("/api/v1/stories",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({content,emoji,imageUrl:image||null,audience,hiddenUserIds:hidden.split(/[\s,]+/).filter(Boolean)})});const data=await response.json();if(!response.ok)throw Error(data.message);setCompose(false);setContent("");setEmoji("");setImage("");await refresh()}catch(reason){setError(reason instanceof Error?reason.message:"Не удалось создать историю.")}finally{setBusy(false)}}
 async function act(story:Story,action:"view"|"react",reaction?:string){const response=await fetch(`/api/v1/stories/${story.id}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,emoji:reaction})});if(response.ok)await refresh()}
 async function remove(story:Story){const response=await fetch(`/api/v1/stories/${story.id}`,{method:"DELETE"});if(response.ok){setSelected(null);await refresh()}}
 return <div className="story-widget"><div className="story-strip"><button onClick={()=>setCompose(true)} aria-label="Добавить историю"><span><Plus/></span><small>Ваша история</small></button>{stories.map(story=><button key={story.id} onClick={()=>{setSelected(story);void act(story,"view")}} aria-label={`История: ${story.name}`}><span className={story.viewed?"seen":""}>{story.avatarUrl?<img src={story.avatarUrl} alt=""/>:story.emoji||story.name.slice(0,2)}</span><small>{story.name}</small></button>)}</div>{compose||selected?<div className="story-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget){setSelected(null);setCompose(false)}}}><section className="story-sheet" role="dialog" aria-modal="true" aria-label={compose?"Новая история":"История"}><button className="story-close" onClick={()=>{setSelected(null);setCompose(false)}} aria-label="Закрыть"><X/></button>{compose?<><h3>Новая история</h3><p>Появится на 24 часа у выбранной аудитории.</p><textarea maxLength={280} value={content} onChange={event=>setContent(event.target.value)} placeholder="Что происходит?"/><input value={emoji} maxLength={12} onChange={event=>setEmoji(event.target.value)} placeholder="Эмодзи" aria-label="Эмодзи истории"/><select value={audience} onChange={event=>setAudience(event.target.value)} aria-label="Кому показать"><option value="friends">Друзьям</option><option value="clan">Участникам клана</option><option value="both">Друзьям и клану</option></select><input value={hidden} onChange={event=>setHidden(event.target.value)} placeholder="Скрыть от ID пользователей через запятую" aria-label="Скрыть от пользователей"/><input ref={uploadRef} hidden type="file" accept="image/png,image/jpeg,image/webp,image/gif" onChange={event=>{const file=event.target.files?.[0];if(file)void upload(file)}}/><button onClick={()=>uploadRef.current?.click()}><ImagePlus size={17}/> {image?"Изображение загружено":"Добавить изображение"}</button>{image?<img className="story-image" src={image} alt="Предпросмотр"/>:null}<button disabled={busy||!content.trim()&&!emoji&&!image} onClick={()=>void create()}>Опубликовать</button></>:selected?<><h3>{selected.emoji} {selected.name}</h3>{selected.imageUrl?<img className="story-image" src={selected.imageUrl} alt="Изображение истории"/>:null}<p>{selected.content}</p><small>До {new Date(selected.expiresAt).toLocaleString("ru-RU")} · {selected.audience==="clan"?"Клан":selected.audience==="friends"?"Друзья":"Друзья и клан"}</small>{selected.userId===userId?<><p>Просмотры: {selected.viewCount??0}</p><button onClick={()=>void remove(selected)}>Удалить историю</button></>:<div className="story-reactions">{["❤️","🔥","😂","👏","✨","💜"].map(value=><button key={value} onClick={()=>void act(selected,"react",value)} aria-label={`Реакция ${value}`}>{value}</button>)}</div>}</>:null}{error?<p role="alert">{error}</p>:null}</section></div>:null}</div>
}
