"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import { Mic, MicOff, PhoneOff, Users } from "lucide-react";
import { Room, RoomEvent, Track } from "livekit-client";
type VoiceRoom={id:string;creatorId:string;expiresAt:string};
export function TemporaryVoice({contextType,contextId,inviteUserId}:{contextType:"direct"|"clan";contextId:string;inviteUserId?:string}){
 const [rooms,setRooms]=useState<VoiceRoom[]>([]),[active,setActive]=useState(""),[muted,setMuted]=useState(false),[names,setNames]=useState<string[]>([]),[error,setError]=useState(""),[busy,setBusy]=useState(false);const roomRef=useRef<Room|null>(null),audio=useRef<HTMLDivElement>(null);
 const refresh=useCallback(async()=>{if(!contextId)return;const query=new URLSearchParams({contextType,contextId});const response=await fetch(`/api/v1/temporary-voice?${query}`,{cache:"no-store"});if(response.ok)setRooms((await response.json()).rooms??[])},[contextType,contextId]);
 useEffect(()=>{void refresh();const timer=window.setInterval(()=>void refresh(),20000);return()=>window.clearInterval(timer)},[refresh]);
 useEffect(()=>()=>{void roomRef.current?.disconnect()},[]);
 async function join(id:string){setBusy(true);setError("");const room=new Room();try{const response=await fetch(`/api/v1/temporary-voice/${id}`,{method:"POST"}),data=await response.json();if(!response.ok)throw Error(data.message);room.on(RoomEvent.TrackSubscribed,track=>{if(track.kind===Track.Kind.Audio)audio.current?.appendChild(track.attach())});room.on(RoomEvent.TrackUnsubscribed,track=>track.detach().forEach(node=>node.remove()));const update=()=>setNames([room.localParticipant.name||"Вы",...[...room.remoteParticipants.values()].map(person=>person.name||"Участник")]);room.on(RoomEvent.ParticipantConnected,update);room.on(RoomEvent.ParticipantDisconnected,update);await room.connect(data.url,data.token);await room.localParticipant.setMicrophoneEnabled(true);roomRef.current=room;setActive(id);update()}catch(reason){await room.disconnect();setError(reason instanceof Error?reason.message:"Не удалось подключиться.")}finally{setBusy(false)}}
 async function create(){setBusy(true);setError("");try{const response=await fetch("/api/v1/temporary-voice",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({contextType,contextId,inviteUserId})}),data=await response.json();if(!response.ok)throw Error(data.message);await refresh();await join(data.room.id)}catch(reason){setError(reason instanceof Error?reason.message:"Не удалось создать комнату.");setBusy(false)}}
 async function leave(){await roomRef.current?.disconnect();roomRef.current=null;setActive("");setNames([])}
 return <section className="temporary-voice" aria-label="Временные голосовые комнаты"><div ref={audio} aria-hidden="true"/><div className="temporary-voice-heading"><strong><Users size={16}/> Голосовые комнаты</strong><button onClick={()=>void create()} disabled={busy||!contextId}><Mic size={16}/> Позвать</button></div>{error?<p role="alert">{error}</p>:null}{rooms.map(room=><div key={room.id} className="temporary-voice-row"><span>Разговор до {new Date(room.expiresAt).toLocaleTimeString("ru-RU",{hour:"2-digit",minute:"2-digit"})}</span>{active===room.id?<><button onClick={async()=>{const next=!muted;await roomRef.current?.localParticipant.setMicrophoneEnabled(!next);setMuted(next)}} aria-label={muted?"Включить микрофон":"Выключить микрофон"}>{muted?<MicOff size={17}/>:<Mic size={17}/>}</button><button onClick={()=>void leave()} aria-label="Выйти"><PhoneOff size={17}/></button></>:<button disabled={busy||Boolean(active)} onClick={()=>void join(room.id)}>Войти</button>}</div>)}{active?<small>В комнате: {names.join(", ")}</small>:null}</section>
}
