import { randomUUID } from "node:crypto";
import { and, asc, eq } from "drizzle-orm";
import { NextResponse } from "next/server";
import { getDatabase } from "@/db/client";
import { boardItems, channels, members } from "@/db/schema";
import { getCurrentUser } from "@/lib/auth";

async function access(channelId: string) { const user = await getCurrentUser(); if (!user) return { error: NextResponse.json({ message: "Требуется вход." }, { status: 401 }) }; const database = getDatabase(); const [channel] = await database.select({ id: channels.id }).from(channels).innerJoin(members, and(eq(members.spaceId, channels.spaceId), eq(members.userId, user.id))).where(and(eq(channels.id, channelId), eq(channels.kind, "board"))).limit(1); if (!channel) return { error: NextResponse.json({ message: "Доска недоступна." }, { status: 403 }) }; return { database, user }; }
export async function GET(_: Request, { params }: { params: Promise<{ channelId: string }> }) { const { channelId } = await params; const result = await access(channelId); if ("error" in result) return result.error; return NextResponse.json({ items: await result.database.select().from(boardItems).where(eq(boardItems.channelId, channelId)).orderBy(asc(boardItems.position), asc(boardItems.createdAt)) }); }
export async function POST(request: Request, { params }: { params: Promise<{ channelId: string }> }) { const { channelId } = await params; const result = await access(channelId); if ("error" in result) return result.error; const body = await request.json().catch(() => null); const title = String(body?.title ?? "").trim().slice(0, 120); if (!title) return NextResponse.json({ message: "Введите название карточки." }, { status: 400 }); const [item] = await result.database.insert(boardItems).values({ id: randomUUID(), channelId, authorId: result.user.id, title, description: String(body?.description ?? "").trim().slice(0, 500) || null }).returning(); return NextResponse.json({ item }, { status: 201 }); }
export async function PATCH(request: Request, { params }: { params: Promise<{ channelId: string }> }) { const { channelId } = await params; const result = await access(channelId); if ("error" in result) return result.error; const body = await request.json().catch(() => null); const status = ["todo", "progress", "done"].includes(body?.status) ? body.status : null; if (!status) return NextResponse.json({ message: "Неизвестный статус." }, { status: 400 }); await result.database.update(boardItems).set({ status, updatedAt: new Date() }).where(and(eq(boardItems.id, String(body.id)), eq(boardItems.channelId, channelId))); return NextResponse.json({ status }); }
export async function DELETE(request: Request, { params }: { params: Promise<{ channelId: string }> }) { const { channelId } = await params; const result = await access(channelId); if ("error" in result) return result.error; const id = new URL(request.url).searchParams.get("id") ?? ""; await result.database.delete(boardItems).where(and(eq(boardItems.id, id), eq(boardItems.channelId, channelId))); return NextResponse.json({ ok: true }); }
