import "server-only";
import { createCipheriv, createDecipheriv, createHash, createHmac, randomBytes, timingSafeEqual } from "node:crypto";

const alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ234567";
export function createTotpSecret() { const bytes = randomBytes(20); let bits = ""; for (const byte of bytes) bits += byte.toString(2).padStart(8, "0"); let output = ""; for (let i = 0; i < bits.length; i += 5) output += alphabet[Number.parseInt(bits.slice(i, i + 5).padEnd(5, "0"), 2)]; return output; }
function decodeBase32(value: string) { let bits = ""; for (const char of value.replace(/=+$/g, "").toUpperCase()) { const index = alphabet.indexOf(char); if (index >= 0) bits += index.toString(2).padStart(5, "0"); } const bytes: number[] = []; for (let i = 0; i + 8 <= bits.length; i += 8) bytes.push(Number.parseInt(bits.slice(i, i + 8), 2)); return Buffer.from(bytes); }
function codeAt(secret: string, counter: number) { const data = Buffer.alloc(8); data.writeBigUInt64BE(BigInt(counter)); const digest = createHmac("sha1", decodeBase32(secret)).update(data).digest(); const offset = digest[digest.length - 1] & 15; const value = (digest.readUInt32BE(offset) & 0x7fffffff) % 1_000_000; return value.toString().padStart(6, "0"); }
export function verifyTotp(secret: string, code: string, now = Date.now()) { const clean = code.replace(/\s/g, ""); if (!/^\d{6}$/.test(clean)) return false; const counter = Math.floor(now / 30_000); return [-1, 0, 1].some((delta) => timingSafeEqual(Buffer.from(codeAt(secret, counter + delta)), Buffer.from(clean))); }
function encryptionKey() { const source = process.env.TOTP_ENCRYPTION_KEY ?? process.env.SETUP_SECRET; if (!source) throw new Error("TOTP_ENCRYPTION_KEY is not configured"); return createHash("sha256").update(source).digest(); }
export function encryptTotpSecret(secret: string) { const iv = randomBytes(12); const cipher = createCipheriv("aes-256-gcm", encryptionKey(), iv); const encrypted = Buffer.concat([cipher.update(secret, "utf8"), cipher.final()]); return [iv, cipher.getAuthTag(), encrypted].map((part) => part.toString("base64url")).join("."); }
export function decryptTotpSecret(payload: string) { const [iv, tag, encrypted] = payload.split(".").map((part) => Buffer.from(part, "base64url")); const decipher = createDecipheriv("aes-256-gcm", encryptionKey(), iv); decipher.setAuthTag(tag); return Buffer.concat([decipher.update(encrypted), decipher.final()]).toString("utf8"); }
export function hashBackupCode(code: string) { return createHash("sha256").update(code.replace(/\s/g, "").toUpperCase()).digest("hex"); }
